name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: './docs/package-lock.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd docs
          npm ci

      - name: Build
        run: |
          cd docs
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          force_orphan: true
          commit_message: "Deploy: ${GITHUB_SHA}"