name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      
      - name: Build WASM Plugins
        run: |
          cd plugins/auth && cargo build --target wasm32-unknown-unknown --release
          cd ../validator && cargo build --target wasm32-unknown-unknown --release
          cd ../logger && cargo build --target wasm32-unknown-unknown --release
          
      - name: Generate Checksum
        run: |
          sha256sum plugins/*/target/wasm32-unknown-unknown/release/*.wasm > checksum.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            plugins/*/target/wasm32-unknown-unknown/release/*.wasm
            checksum.txt